spring:
  datasource:
    username: root
    password: '{cipher}AQBQ5anaVq1ZS4uogQuST5Nu39ql4R4ebILqcj/g3PDHud/Wznj+fdI3ihLVm+PBf+XmwXzjDlp/Fdkcu++a+RfvyNWHboQ36G5Wr9znjzAcOk95i/GQmd2y7ZbBtaV7sFJEHYwSAg/o8mOjk5gq7xytmB7wFLu7ufdCaoBc1KiawYWVVerQBNv6J/BgUne/yz3uBHTjCDagjHM+lkUxDo9r2vCYKDEUMADX5rN/GpU9ZRDlWrx98RnCXgbpuXIacqt2UlTiPZLQpNmyK6tw+aDf8QqH2sIk+IVazOce2zKQkarNhXeg05UJySNZyzAeW8z6RqlVmUL1A0u3oSc9d0pvqCEdhkQKe7d/dbC2PTNkCsJRQhjsq5R0h0Naf3CQfi4='